#!/usr/bin/env python3
"""
Whitespace-flexible translation for sph3u_u1la5.html.
Normalizes whitespace in patterns so line breaks don't cause mismatches.
"""
import re

filepath = 'course_content/lessons/sph3u_u1la5.html'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

def flex_replace(content, eng, kor):
    """Replace English text with Korean, flexible on whitespace."""
    # Escape regex special chars in eng, then replace spaces with \s+
    pattern = re.escape(eng)
    pattern = pattern.replace(r'\ ', r'\s+')
    # Also handle escaped newlines
    pattern = pattern.replace(r'\n', r'\s+')
    try:
        result = re.sub(pattern, kor, content, count=1)
        if result == content:
            return content, False
        return result, True
    except:
        return content, False

# All translations as (English, Korean) pairs
# Whitespace in these will be matched flexibly
TRANSLATIONS = [
    # Noscript - has typo "contians"
    ("To ensure the greatest educational experience, this learning activity contians aspects that require Javascript to be enabled.",
     "최상의 학습 경험을 위해, 이 학습 활동은 Javascript가 활성화되어 있어야 합니다."),
    ("<strong>Warning!</strong>", "<strong>주의!</strong>"),

    # Learning goals
    ("We are learning to:", "학습 내용:"),
    ("describe mechanical resonance", "역학적 공명을 설명한다"),
    ("identify sympathetic vibration", "공감 진동을 식별한다"),
    ("calculate resonant frequencies using", "다음을 사용하여 공명 진동수를 계산한다:"),
    ("apply equations involving resonance in air columns", "공기 기둥에서의 공명과 관련된 방정식을 적용한다"),
    ("study the application of resonance in musical instruments", "악기에서의 공명 응용을 학습한다"),
    ("I am able to:", "나는 다음을 할 수 있다:"),
    ("describe when and how resonance occurs", "공명이 언제, 어떻게 발생하는지 설명할 수 있다"),
    ("describe the difference between closed and open-air columns", "닫힌 공기 기둥과 열린 공기 기둥의 차이를 설명할 수 있다"),
    ("calculate the resonant lengths of air columns", "공기 기둥의 공명 길이를 계산할 수 있다"),
    ("describe how resonance is used in musical instruments", "악기에서 공명이 어떻게 사용되는지 설명할 수 있다"),

    # Vocabulary
    ("Vocabulary: Record the following vocabulary in your notebook. As you complete the learning activity fill in the definition and key terminology pertaining to the vocabulary:",
     "어휘: 다음 어휘를 노트에 기록하세요. 학습 활동을 완료하면서 어휘에 관련된 정의와 핵심 용어를 채워 넣으세요:"),
    ("<li>amplify </li>", "<li>증폭 </li>"),
    ("<li>resonance </li>", "<li>공명 </li>"),

    # Introduction
    ("How can a musical instrument like a trumpet make such a loud noise when the musician barely makes a sound blowing into it?",
     "트럼펫 같은 악기는 음악가가 겨우 소리를 불어넣는데 어떻게 그렇게 큰 소리를 낼 수 있을까요?"),
    ("It's because the length of the tube that the trumpet is made from naturally amplifies certain frequencies of sound. These frequencies are called natural frequencies or resonant frequencies.",
     "이는 트럼펫을 이루는 관의 길이가 자연적으로 특정 진동수의 소리를 증폭시키기 때문입니다. 이러한 진동수를 고유 진동수 또는 공명 진동수라고 합니다."),
    ("Most objects have resonant frequencies at which they naturally vibrate. Sometimes the results of this vibration can be spectacular.",
     "대부분의 물체는 자연적으로 진동하는 공명 진동수를 가지고 있습니다. 때때로 이 진동의 결과는 놀라울 수 있습니다."),
    ("When an earthquake strikes, some buildings will completely collapse, while other buildings nearby will only be slightly damaged.",
     "지진이 발생하면 일부 건물은 완전히 무너지는 반면, 근처의 다른 건물들은 약간만 손상됩니다."),
    ("Something other than the strength of the earthquake determines how much damage occurs.",
     "지진의 강도 외의 다른 요인이 피해 정도를 결정합니다."),
    ("If a building has a resonant frequency that is close to the frequency of an earthquake, the building will shake dramatically during the quake and may even collapse, while nearby buildings stand firm.",
     "건물의 공명 진동수가 지진의 진동수에 가까우면, 지진 중 건물이 극적으로 흔들리고 무너질 수도 있는 반면, 근처 건물들은 견고하게 서 있습니다."),
    ("There are steps that can be taken to keep buildings safe from earthquakes.",
     "지진으로부터 건물을 안전하게 유지하기 위해 취할 수 있는 조치들이 있습니다."),
    ("What instruments can you think of? Can you describe how they vibrate to make noise?",
     "어떤 악기들을 떠올릴 수 있나요? 소리를 내기 위해 어떻게 진동하는지 설명할 수 있나요?"),
    ("Examples of musical instruments are drum, violin, flute, human voice, etc.",
     "악기의 예로는 드럼, 바이올린, 플루트, 사람의 목소리 등이 있습니다."),
    ("What vibrates to produce sound for different musical instruments are skin of the drum, string of the violin, air in the flute, vocal chords, etc.",
     "다른 악기에서 소리를 내기 위해 진동하는 것은 드럼의 가죽, 바이올린의 현, 플루트의 공기, 성대 등입니다."),

    # Explore sections
    ("Explore the following short video of a toy used by children.", "어린이들이 사용하는 장난감에 대한 다음 짧은 영상을 탐구하세요."),
    ("What is causing the sound made by the toy?", "장난감에서 나는 소리의 원인은 무엇인가요?"),
    ("Air in the tube is vibrating at different frequencies.", "관 안의 공기가 다양한 진동수로 진동하고 있습니다."),
    ("What a person just heard is resonance in an air column. This is similar to blowing across the top of a glass or plastic bottle. It is the air that is vibrating inside the container.",
     "방금 들은 것은 공기 기둥에서의 공명입니다. 이것은 유리잔이나 플라스틱 병의 윗부분을 가로질러 바람을 불어넣는 것과 유사합니다. 진동하는 것은 용기 안의 공기입니다."),
    ("The concept of resonance can be used to create beautiful sounds in musical instruments as well. You will now explore how resonance is all around us.",
     "공명의 개념은 악기에서도 아름다운 소리를 만드는 데 사용될 수 있습니다. 이제 공명이 우리 주변에 어떻게 있는지 탐구합니다."),

    # Mechanical resonance
    ("역학적 공명 occurs when a source of periodic vibrations causes an object to vibrate back and forth with large amplitudes of motion, through direct contact. It occurs when the frequency of the periodic force is equal to the natural frequency of the object.",
     "역학적 공명은 주기적 진동의 원천이 직접 접촉을 통해 물체를 큰 진폭으로 앞뒤로 진동하게 할 때 발생합니다. 주기적 힘의 진동수가 물체의 고유 진동수와 같을 때 발생합니다."),
    ("When this happens, the object begins to rock back and forth, or resonate, with very large amplitudes. The results of resonance always seem surprising, because such a small force seems to cause so much motion.",
     "이 경우, 물체는 매우 큰 진폭으로 앞뒤로 흔들리거나 공명하기 시작합니다. 공명의 결과는 항상 놀랍게 보입니다. 왜냐하면 그렇게 작은 힘이 그렇게 큰 운동을 일으키는 것처럼 보이기 때문입니다."),
    ("Small pushes of a child on a swing can cause a large amplitude of vibration (a big swinging motion) if the pushes have the same natural frequency as the swing.",
     "그네의 고유 진동수와 같은 진동수로 밀면, 아이를 그네에서 작게 미는 것만으로도 큰 진폭의 진동(큰 흔들림)을 일으킬 수 있습니다."),

    # Pendulum
    ("Another simple example of resonance can be demonstrated by tying several pendula (plural for pendulum) to the same support string. The apparatus is demonstrated in the following video.",
     "공명의 또 다른 간단한 예는 여러 개의 진자(pendulum의 복수형)를 같은 지지 끈에 묶어서 시연할 수 있습니다. 장치는 다음 영상에서 보여줍니다."),
    ("Press here for a long description.", "상세 설명을 보려면 여기를 누르세요."),
    ("The period of a pendulum with small amplitudes of vibration depends only on its length. In this case, the diagram demonstrates two pendula with the same length (1 and 4), and two others with different lengths (2 and 3).",
     "작은 진폭의 진동을 하는 진자의 주기는 길이에만 의존합니다. 이 경우, 그림은 같은 길이의 두 진자(1과 4)와 다른 길이의 두 진자(2와 3)를 보여줍니다."),
    ("Give pendulum 1 a push, it will move back and forth over and over again, while the other three pendula will hardly move at all. The same will happen by giving pendulum 3 a push.",
     "진자 1을 밀면, 계속해서 앞뒤로 움직이지만 나머지 세 진자는 거의 움직이지 않습니다. 진자 3을 밀어도 마찬가지입니다."),
    ("However, giving pendulum 2 a push, something strange happens. Pendulums 1 and 3 will hardly move at all, but pendulum 4 will start to rock back and forth with large amplitudes after several seconds.",
     "그러나 진자 2를 밀면 이상한 일이 일어납니다. 진자 1과 3은 거의 움직이지 않지만, 진자 4는 몇 초 후 큰 진폭으로 앞뒤로 흔들리기 시작합니다."),
    ("When this happens, pendulum 2 will start to decrease in amplitude and eventually come to a stop. However, after a second or two, pendulum 2 will start to swing again, developing large amplitudes of vibration, while pendulum 4 starts to settle down.",
     "이 때 진자 2는 진폭이 줄어들기 시작하여 결국 멈춥니다. 그러나 1~2초 후, 진자 2가 다시 흔들리기 시작하여 큰 진폭의 진동을 발전시키고, 진자 4는 안정되기 시작합니다."),
    ("Note that both pendulums 2 and 4 have the same natural frequency, while the other two pendulums have different frequencies. When pendulum 2 starts to move back and forth, it causes a small periodic vibration in the horizontal string that supports all of the other pendulums. When one object vibrates in resonance with another, it is called a sympathetic vibration. The small vibrations in this string will have the same frequency as both pendulums 2 and 4,",
     "진자 2와 4는 같은 고유 진동수를 가지고 있고, 나머지 두 진자는 다른 진동수를 가집니다. 진자 2가 앞뒤로 움직이기 시작하면, 다른 모든 진자를 지지하는 수평 끈에 작은 주기적 진동을 일으킵니다. 한 물체가 다른 물체와 공명하여 진동할 때, 이를 공감 진동이라고 합니다. 이 끈의 작은 진동은 진자 2와 4 모두와 같은 진동수를 가지므로,"),
    # Handle the "so they can cause" part separately since it may be "따라서" already
    ("they can cause resonance in these two pendulums. These small vibrations in the horizontal support string don't have the same frequency as the other two,",
     "이 두 진자에서 공명을 일으킬 수 있습니다. 수평 지지 끈의 이 작은 진동은 나머지 두 진자와 같은 진동수를 가지지 않으므로,"),
    ("no resonance occurs in pendulums 1 and 3.", "진자 1과 3에서는 공명이 발생하지 않습니다."),

    # Sympathetic vibrations
    ("Sympathetic vibrations", "공감 진동"),
    ("The previous example demonstrates the concept of sympathetic vibrations. The two pendula with the same natural frequency resonated together.",
     "이전 예제는 공감 진동의 개념을 보여줍니다. 같은 고유 진동수를 가진 두 진자가 함께 공명했습니다."),
    ("Play the following video to understand how sympathetic vibrations occur in tuning forks.",
     "다음 영상을 통해 소리굽쇠에서 공감 진동이 어떻게 발생하는지 이해하세요."),

    # Wine glass
    ("The following video demonstrates the effects of resonance. The speaker that is to the left of the wine glass has the same frequency as the natural frequency of the glass. The resonance of the glass causes it to vibrate with large amplitude and eventually break.",
     "다음 영상은 공명의 효과를 보여줍니다. 와인 잔 왼쪽의 스피커는 유리잔의 고유 진동수와 같은 진동수를 가지고 있습니다. 유리잔의 공명은 큰 진폭으로 진동하게 하여 결국 깨지게 합니다."),

    # Tuning fork boxes
    ("By striking the tuning fork attached to the box, it is much louder and a person can hear it clearly across a room.",
     "상자에 부착된 소리굽쇠를 치면 훨씬 크게 들리며 방 건너편에서도 명확하게 들을 수 있습니다."),
    ("If two tuning forks with equal frequencies are mounted on two different boxes and near each other, as identified in the first video, sympathetic vibrations can be observed.",
     "첫 번째 영상에서 보여준 것처럼, 같은 진동수의 두 소리굽쇠가 서로 가까운 두 다른 상자에 장착되면 공감 진동을 관찰할 수 있습니다."),
    ("If one tuning fork is struck, the other one will start to vibrate shortly afterwards and will produce a sound as well. This is a good example of resonance.",
     "하나의 소리굽쇠를 치면, 다른 소리굽쇠도 곧 진동하기 시작하여 소리를 냅니다. 이것은 공명의 좋은 예입니다."),
    ("The sound wave in the air from one tuning fork hits the other and starts to make it vibrate. Since they have the same frequency, the second tuning fork will also make a loud sound.",
     "한 소리굽쇠의 공기 중 음파가 다른 소리굽쇠에 도달하여 진동하게 합니다. 같은 진동수를 가지므로, 두 번째 소리굽쇠도 큰 소리를 냅니다."),
    ("By attaching a weight to one fork, the frequencies no longer match and we do not observe sympathetic vibrations. We can verify that the frequencies are different because, when both forks are struck, beats are heard in the tones.",
     "한 소리굽쇠에 무게를 달면 진동수가 더 이상 일치하지 않아 공감 진동이 관찰되지 않습니다. 두 소리굽쇠를 모두 쳤을 때 맥놀이가 들리므로 진동수가 다르다는 것을 확인할 수 있습니다."),

    # Speaker/bridge
    ("If the speaker was producing sound at a frequency different than the natural frequency of the glass, the glass would not vibrate with such a large amplitude and it would not break.",
     "스피커가 유리잔의 고유 진동수와 다른 진동수의 소리를 내고 있었다면, 유리잔은 그렇게 큰 진폭으로 진동하지 않았을 것이고 깨지지 않았을 것입니다."),
    ("Another dramatic example of resonance is the Tacoma Narrows bridge. Wind gusts blowing with the same frequency as the natural frequency of the bridge cause huge vibrations in the bridge, eventually causing it to collapse.",
     "공명의 또 다른 극적인 예는 타코마 내로스 다리입니다. 다리의 고유 진동수와 같은 진동수로 불어오는 돌풍이 다리에 거대한 진동을 일으켜 결국 붕괴시켰습니다."),
    ("The following video provides further explanation for the Tacoma Narrow bridge.",
     "다음 영상은 타코마 내로스 다리에 대한 추가 설명을 제공합니다."),
    ("If the wind had been blowing with a frequency that was not the same as the natural frequency of the bridge, the vibrations would not have become so large and the bridge would probably still be standing.",
     "바람이 다리의 고유 진동수와 같지 않은 진동수로 불고 있었다면, 진동이 그렇게 커지지 않았을 것이고 다리는 아마 아직도 서 있었을 것입니다."),

    # Car in snow
    ("Imagine that a car gets stuck in the snow. When trying to push it out, deep ruts form. How could we use resonance to help push the car out while someone else is driving?",
     "자동차가 눈에 빠졌다고 상상해 보세요. 밀어내려고 할 때 깊은 바퀴 자국이 형성됩니다. 다른 사람이 운전하는 동안 공명을 이용하여 어떻게 자동차를 밀어낼 수 있을까요?"),
    ("If people push the car from behind, people might be able to rock it back and forth, but people probably wouldn't be able to push it right out with one shove. When the car is rocking back and forth, people could match the frequency of the car's motion to the frequency of people's pushes. This use of resonance would increase the amplitude of the car's motion. Eventually, the car will rock back and forth enough so that the person driving is able to drive the car out of the ruts.",
     "사람들이 뒤에서 자동차를 밀면 앞뒤로 흔들 수 있지만, 한 번에 밀어낼 수는 없을 것입니다. 자동차가 앞뒤로 흔들릴 때, 자동차 운동의 진동수에 미는 진동수를 맞출 수 있습니다. 이런 공명의 사용은 자동차 운동의 진폭을 증가시킵니다. 결국, 자동차가 충분히 앞뒤로 흔들려서 운전하는 사람이 바퀴 자국에서 빠져나올 수 있게 됩니다."),

    # Soldiers
    ("Why is it dangerous for a group of marching soldiers to cross a small footbridge together, while they are marching in unison?",
     "행진하는 병사들이 보조를 맞추며 작은 보행교를 함께 건너는 것이 왜 위험한가요?"),
    ("If the frequency of the marching soldiers matches the natural frequency of the footbridge, the bridge could start to resonate and experience large amplitudes of vibration. These vibrations might be large enough to make the soldiers lose their footing or might even damage the bridge.",
     "행진하는 병사들의 진동수가 보행교의 고유 진동수와 일치하면, 다리가 공명하기 시작하여 큰 진폭의 진동을 경험할 수 있습니다. 이 진동은 병사들이 발을 헛디디게 하거나 다리를 손상시킬 만큼 클 수 있습니다."),

    # Standing waves in strings
    ("As you may recall, standing waves in strings are produced when two identical waves travel in opposite directions in the same medium.",
     "기억하시겠지만, 현에서의 정상파는 두 개의 동일한 파동이 같은 매질에서 반대 방향으로 이동할 때 만들어집니다."),
    ("The following diagram has three", "다음 그림에는 세 개의"),
    ("Each loop has a length of half of a wavelength.", "각 루프는 파장의 절반 길이를 가집니다."),
    ("Standing waves can be formed with any number of", "정상파는 몇 개의"),
    ("Start by considering a string, anchored at both ends. This is referred to as a string with two fixed ends.",
     "양쪽 끝에 고정된 현을 생각해 봅시다. 이것을 양쪽 끝이 고정된 현이라고 합니다."),
    ("All stringed instruments, like guitars and violins, have strings with fixed ends.",
     "기타와 바이올린 같은 모든 현악기는 끝이 고정된 현을 가지고 있습니다."),
    ("Since the string is fixed at both ends, there must be", "현이 양쪽 끝에 고정되어 있으므로,"),
    ("at these points, even if a standing wave is present in the string.", "정상파가 현에 존재하더라도 이 지점들에는 마디가 있어야 합니다."),
    ("This means that the frequencies that produce a standing wave must make one loop, or two", "이것은 정상파를 만드는 진동수가 하나의 루프, 또는 두 개의"),
    ("Since only certain numbers of", "특정 수의"),
    ("are possible, the wavelength can only be selected from a limited number of lengths.",
     "만 가능하므로, 파장은 제한된 수의 길이에서만 선택될 수 있습니다."),
    ("One wavelength corresponds to a single loop, another to two", "하나의 파장은 하나의 루프에 해당하고, 다른 것은 두 개의"),
    (", another to three", ", 또 다른 것은 세 개의"),
    ("In addition, the speed of vibration in the string is a property of the material and tension on the string,",
     "또한, 현에서의 진동 속력은 현의 재질과 장력의 특성이므로,"),
    ("it is a fixed value.", "고정된 값입니다."),
    ("this means that only certain frequencies can produce standing waves in a fixed string.",
     "고정된 현에서 정상파를 만들 수 있는 진동수는 특정한 것만 가능합니다."),
    ("Also, the speed of vibration does not change", "또한, 진동 속력은 변하지 않으므로"),
    ("the number of loops determines the frequency of the standing wave. This sounds exactly like resonance!",
     "루프의 수가 정상파의 진동수를 결정합니다. 이것은 마치 공명과 같습니다!"),

    # String example
    ("The following example will help to clarify this concept.", "다음 예제가 이 개념을 명확히 하는 데 도움이 될 것입니다."),
    ("Consider a string of length L stretched tightly between two fixed positions.",
     "길이 L의 현이 두 고정 위치 사이에 팽팽하게 당겨져 있다고 생각해 봅시다."),
    ("In a stringed instrument, these would be the two ends of the string attached to the instrument.",
     "현악기에서 이것은 악기에 부착된 현의 양쪽 끝입니다."),
    ("Since only one loop is present, the length of the string is half of a wavelength.",
     "루프가 하나만 있으므로, 현의 길이는 파장의 절반입니다."),
    ("This can be rearranged to", "이것을 다시 정리하면"),
    ("Since this is for the frequency that creates a single", "이것은 단일"),
    ("this is called the fundamental frequency.",
     "을 만드는 진동수이므로, 기본 진동수라고 합니다."),
    ("This is called the fundamental frequency.", "이것을 기본 진동수라고 합니다."),
    ("It is the lowest frequency that will produce a standing wave in the string.",
     "이것은 현에서 정상파를 만들 수 있는 가장 낮은 진동수입니다."),
    ("If the frequency is increased,", "진동수를 증가시키면,"),
    ("will not produce a standing wave until the frequency is high enough that two",
     "진동수가 충분히 높아져 두 개의"),
    ("fit in the string.", "이 현에 들어맞을 때까지 정상파를 만들지 못합니다."),
    ("If the frequency continues to increase, another standing wave will form with three",
     "진동수를 계속 증가시키면, 세 개의"),
    ("The frequency that causes a standing wave with two", "두 개의"),
    ("is called the second harmonic.", "를 가진 정상파를 만드는 진동수를 제2배음이라고 합니다."),
    ("Since it is the same string,", "같은 현이므로,"),
    ("Given the length of the string and the speed of the wave,",
     "현의 길이와 파동의 속력이 주어지면,"),
    ("This is the second smallest frequency that will create a standing wave in the string.",
     "이것은 현에서 정상파를 만드는 두 번째로 작은 진동수입니다."),
    ("Compare the two equations side by side:", "두 공식을 나란히 비교하면:"),
    ("This demonstrates that the frequency that produces two",
     "이것은 두 개의"),
    ("is exactly twice the fundamental frequency.", "를 만드는 진동수가 기본 진동수의 정확히 두 배임을 보여줍니다."),
    ("Continuing to increase the frequency from", ""),
    ("Resonance will not take place again until the frequency increases to",
     "에서 진동수를 계속 증가시키면, 진동수가"),
    ("where three", "로 증가하여 세 개의"),
    ("are formed.", "이 형성될 때까지 공명이 다시 일어나지 않습니다."),
    ("This trend is illustrated in the following table.", "이 경향은 다음 표에 나타나 있습니다."),
    ("Frequency", "진동수"),
    ("Number of", ""),

    # Table/diagram labels
    ("Harmonic", "배음"),
    ("Diagram", "그림"),

    # Practice section
    ("Use your knowledge about standing waves to work through the following example in your notebook. Compare your work with the suggested answers to check your understanding.",
     "정상파에 대한 지식을 사용하여 다음 예제를 노트에 풀어 보세요. 풀이 예시와 비교하여 이해도를 확인하세요."),

    # GUESS structure
    ("State the information given.", "주어진 정보를 적으세요."),
    ("State the variable you want to find.", "구하려는 변수를 적으세요."),
    ("Select an equation that includes the unknown and given values that could lead to a solution.",
     "미지수와 주어진 값을 포함하는 공식을 선택하세요."),
    ("Substitute into the equation and solve for the desired value.",
     "공식에 대입하고 원하는 값을 구하세요."),
    ("Explain any work that isn't obvious, and write a sentence restating the answer to the original question. Include significant digits and units.",
     "명확하지 않은 풀이를 설명하고, 원래 질문에 대한 답을 다시 문장으로 작성하세요. 유효 숫자와 단위를 포함하세요."),

    # Problem texts
    ("1. What is the speed of the waves in the string?",
     "1. 현에서의 파동의 속력은 얼마인가요?"),
    ("The wave travels the full length of the string in the time period.",
     "파동은 주기 동안 현의 전체 길이를 이동합니다."),

    # Lots more content that the agents found - handle remaining big blocks
    # Air column content
    ("The following video exhibits equipment that can be used to investigate resonance in a closed air column.",
     "다음 영상은 닫힌 공기 기둥에서 공명을 조사하는 데 사용할 수 있는 장비를 보여줍니다."),
    ("A closed air column is just a long container with air in it, but the container is open at one end and closed at the other.",
     "닫힌 공기 기둥은 공기가 들어 있는 긴 용기로, 한쪽 끝은 열려 있고 다른 쪽 끝은 닫혀 있습니다."),
    ("In the following setup, water is used to close the bottom end of the cylinder.",
     "다음 실험 장치에서는 물을 사용하여 원통의 바닥 끝을 닫습니다."),
    ("Placing a tuning fork at the top of the closed air column will send sound down into the column.",
     "닫힌 공기 기둥 위에 소리굽쇠를 놓으면 소리가 기둥 아래로 전달됩니다."),
    ("The sound can reflect off the water and move back up through the closed air column, producing a standing wave of sound.",
     "소리는 물에서 반사되어 닫힌 공기 기둥을 통해 다시 위로 올라가며, 소리의 정상파를 만들 수 있습니다."),
    ("The water will act like a fixed end, meaning that there will always be a node at the bottom of the closed air column.",
     "물은 고정 끝처럼 작용하여, 닫힌 공기 기둥의 바닥에는 항상 마디가 있습니다."),
    ("If an antinode (wide part of the wave) is located at the top of the closed air column, a person will hear a much louder sound coming from the tuning fork than would normally be heard, due to resonance.",
     "배(파동의 넓은 부분)가 닫힌 공기 기둥의 꼭대기에 위치하면, 공명으로 인해 소리굽쇠에서 평소보다 훨씬 큰 소리가 들립니다."),
    ("This is very similar to the standing waves produced in strings. In strings, both ends were nodes. In this type of air column, one end will be a node and one end will be an antinode.",
     "이것은 현에서 만들어지는 정상파와 매우 유사합니다. 현에서는 양쪽 끝이 마디였습니다. 이 유형의 공기 기둥에서는 한쪽 끝이 마디이고 다른 쪽 끝이 배입니다."),
    ("The shortest air column that will produce resonance with the tuning fork is demonstrated in the following simplified diagram.",
     "소리굽쇠와 공명을 만드는 가장 짧은 공기 기둥이 다음 간략화된 그림에 나타나 있습니다."),
    ("In this case, since only half of a loop is present, the length of air column is:",
     "이 경우, 루프의 절반만 있으므로 공기 기둥의 길이는:"),
    ("If the air column is raised, there will no longer be a loud sound. Eventually, another antinode will be positioned at the top of the air column and resonance will take place again, producing another loud sound. In this case, one complete loop and half of a loop will fit inside the air column.",
     "공기 기둥을 올리면 더 이상 큰 소리가 나지 않습니다. 결국 다른 배가 공기 기둥의 꼭대기에 위치하게 되고 다시 공명이 일어나 큰 소리가 납니다. 이 경우, 완전한 루프 하나와 루프의 절반이 공기 기둥 안에 들어갑니다."),
    ("As previously mentioned, one loop has a length equal to half the wavelength of the wave. In this case, the second resonant length of the air column is:",
     "앞서 언급했듯이, 하나의 루프는 파동 파장의 절반과 같은 길이를 가집니다. 이 경우, 공기 기둥의 두 번째 공명 길이는:"),
    ("If we know the frequency of the sound wave, we can calculate the length of the closed air column that is needed to create a resonant length. The resonant length is important because that is what creates the loud sound. If the air column was not the correct length, the sound would not get amplified because there would be no resonance.",
     "음파의 진동수를 알면, 공명 길이를 만드는 데 필요한 닫힌 공기 기둥의 길이를 계산할 수 있습니다. 공명 길이는 큰 소리를 만드는 것이기 때문에 중요합니다. 공기 기둥이 올바른 길이가 아니면, 공명이 없기 때문에 소리가 증폭되지 않습니다."),
    ("You can use your notebook to complete each of the following questions. Compare your work with the suggested answer to check your understanding. If you need a hint for the questions, press on the hint button.",
     "노트를 사용하여 다음 각 문제를 풀어 보세요. 풀이 예시와 비교하여 이해도를 확인하세요. 문제에 대한 힌트가 필요하면 힌트 버튼을 누르세요."),

    # Closed air column problems
    ("1. The first resonant length of a closed air column is 20 cm. Find the second and third resonant lengths.",
     "1. 닫힌 공기 기둥의 첫 번째 공명 길이는 20 cm입니다. 두 번째와 세 번째 공명 길이를 구하세요."),
    ("Referring to the table above, is there a mathematical relationship between the resonant lengths that you could use here? Perhaps try writing out the given and unknown values, and finding an equation that incorporates both of those values.",
     "위의 표를 참고하여, 여기서 사용할 수 있는 공명 길이들 사이의 수학적 관계가 있나요? 주어진 값과 구하는 값을 적어 보고, 두 값을 모두 포함하는 공식을 찾아보세요."),
    ("There are at least two different ways to solve this problem. One way is to use the given length to find the wavelength of the sound waves, then use that to calculate the other resonant lengths. The other is this suggested answer. Either would be accepted.",
     "이 문제를 풀 수 있는 방법은 최소 두 가지입니다. 한 가지는 주어진 길이를 사용하여 음파의 파장을 구한 다음 다른 공명 길이를 계산하는 것입니다. 다른 방법은 이 풀이 예시입니다. 어느 방법이든 허용됩니다."),
    ("Checking the table above, some of the equations we have are:",
     "위의 표를 확인하면, 사용할 수 있는 공식들은 다음과 같습니다:"),
    ("The second resonant length is 60 cm and the third resonant length is 100 cm.",
     "두 번째 공명 길이는 60 cm이고 세 번째 공명 길이는 100 cm입니다."),
    ("Since the given first resonant length had one significant digit, these are reported with one significant digit.",
     "주어진 첫 번째 공명 길이가 유효 숫자 1자리이므로, 1자리로 나타냅니다."),

    # Problem 2
    ("2. What is the shortest air column that will resonate with a tuning fork with a frequency of 460 Hz, when the speed of sound in air is 344 m/s?",
     "2. 공기 중 음속이 344 m/s일 때, 진동수 460 Hz의 소리굽쇠와 공명하는 가장 짧은 공기 기둥의 길이는 얼마인가요?"),
    ("can be used to find the wavelength, at which point the usual resonant length formula can be used.",
     "을 사용하여 파장을 구한 다음, 일반적인 공명 길이 공식을 사용할 수 있습니다."),
    ("First, find the wavelength.", "먼저 파장을 구합니다."),
    ("Keep a few extra decimal places in your written solutions, and do your best to keep the full value in your calculator as you work.",
     "풀이에서 소수점 아래 몇 자리를 더 유지하고, 계산기에서 전체 값을 유지하도록 하세요."),
    ("The shortest air column that will resonate with the given frequency is one measuring 0.19 m.",
     "주어진 진동수와 공명하는 가장 짧은 공기 기둥의 길이는 0.19 m입니다."),

    # Problem 3
    ("3. A tuning fork causes resonance in a pipe with one closed end. The difference between the first resonant length and the second resonant length is 0.390 m. The air temperature is 26.0",
     "3. 소리굽쇠가 한쪽 끝이 닫힌 관에서 공명을 일으킵니다. 첫 번째 공명 길이와 두 번째 공명 길이의 차이는 0.390 m입니다. 공기 온도는 26.0"),
    ("Find the frequency of the turning fork and the third resonant length of the pipe.",
     "소리굽쇠의 진동수와 관의 세 번째 공명 길이를 구하세요."),
    ("Setting out the given and unknown values helps in identifying the appropriate formula(s). If there is more than one equation, they could be combined. In addition, you will need to refer back to the speed of sound formula from earlier in the unit. This solution will be longer than the others we've encountered so far, since it combines multiple areas of knowledge.",
     "주어진 값과 구하는 값을 정리하면 적절한 공식을 찾는 데 도움이 됩니다. 공식이 여러 개이면 결합할 수 있습니다. 또한, 이 단원 앞부분의 음속 공식을 참고해야 합니다. 이 풀이는 여러 지식 영역을 결합하므로 지금까지의 것보다 길 것입니다."),
    ("Use the temperature to find speed, then the difference in resonant lengths to find wavelength. Use those to find frequency. Afterwards, use the wavelength to find the third resonant length.",
     "온도를 사용하여 속력을 구하고, 공명 길이의 차이를 사용하여 파장을 구하세요. 이를 사용하여 진동수를 구하세요. 그 후, 파장을 사용하여 세 번째 공명 길이를 구하세요."),
    ("This is a complicated problem, with multiple steps. Take your time, perform rough work in your notebook, and check your answers. A suggested answer is presented here for you to follow along. If you get stuck, read just the next step and think about whether you can continue from there.",
     "이것은 여러 단계를 가진 복잡한 문제입니다. 시간을 가지고, 노트에 계산을 하고, 답을 확인하세요. 여기에 풀이 예시가 제시되어 있으니 따라가 보세요. 막히면 다음 단계만 읽고 거기서 계속할 수 있는지 생각해 보세요."),
    ("There are many equations that can be combined in this situation. You can start by writing out as many as possible, then remove the ones you don't end up using. The GUESS problem-solving structure is a way to communicate your thinking, but it doesn't mean you can't edit it afterwards to ensure a clean, polished, professional presentation.",
     "이 상황에서는 결합할 수 있는 공식이 많습니다. 가능한 한 많은 공식을 적어 시작한 다음, 사용하지 않는 것을 제거할 수 있습니다. GUESS 문제 풀이 구조는 사고를 전달하는 방법이지만, 깔끔하고 체계적인 발표를 위해 나중에 편집할 수 없다는 의미는 아닙니다."),
    ("First, find the frequency.", "먼저 진동수를 구합니다."),
    ("The question asks for frequency first, then the third resonant length, which implies frequency can be found first. If I try this and get stuck, I can always try the other order and edit this statement.",
     "문제가 진동수를 먼저, 그 다음 세 번째 공명 길이를 묻고 있으므로, 진동수를 먼저 구할 수 있음을 암시합니다. 이 방법으로 시도해 보고 막히면, 순서를 바꿔 시도할 수 있습니다."),
    ("Start with the speed of sound.", "먼저 음속을 구합니다."),
    ("The only one of my formulas that involves frequency is", "제 공식 중 진동수가 포함된 유일한 것은"),
    ("I have speed, so to find frequency I also need to find wavelength.",
     "속력을 알고 있으므로, 진동수를 구하려면 파장도 구해야 합니다."),
    ("and substitute.", "그리고 대입합니다."),
    ("Substituting the wavelength terms,", "파장 항을 대입하면,"),
    ("Use decimals or collect like terms:", "소수로 바꾸거나 동류항을 정리합니다:"),
    ("(either would be appropriate, pick the one you're most comfortable with)",
     "(둘 다 적절합니다, 편한 것을 선택하세요)"),
    ("Use your algebra skills to get the wavelength alone.", "대수학 기술을 사용하여 파장만 남기세요."),
    ("Now that we have both speed and wavelength, we can find frequency.",
     "이제 속력과 파장을 모두 구했으므로, 진동수를 구할 수 있습니다."),
    ('Double-checking the "Unknown" section of GUESS, we have the solution to one part but not the other. We still need the other resonant length.',
     'GUESS의 "구하는 값" 부분을 다시 확인하면, 한 부분의 답은 구했지만 다른 부분은 아직입니다. 다른 공명 길이를 아직 구해야 합니다.'),
    ("The frequency is 445 Hz and the third resonant length is 0.975 m.",
     "진동수는 445 Hz이고 세 번째 공명 길이는 0.975 m입니다."),

    # Problem 4
    ("So far we have analyzed changing the length of a closed air column. If the speed of sound is constant and a closed air column's length is also constant, we can also consider the column as having resonant frequencies by adjusting the wavelength. Apply your knowledge of closed air columns to this new situation by answering the following question.",
     "지금까지 닫힌 공기 기둥의 길이를 변화시키는 것을 분석했습니다. 음속이 일정하고 닫힌 공기 기둥의 길이도 일정하다면, 파장을 조절하여 기둥이 공명 진동수를 가지는 것으로 생각할 수 있습니다. 닫힌 공기 기둥에 대한 지식을 다음 문제에 적용해 보세요."),
    ("4. A ship's whistle is 0.50 m long and is closed at one end. If the speed of sound is 350 m/s, calculate the first and second resonant frequencies for the ship's whistle.",
     "4. 배의 기적은 길이가 0.50 m이고 한쪽 끝이 닫혀 있습니다. 음속이 350 m/s일 때, 배 기적의 첫 번째와 두 번째 공명 진동수를 계산하세요."),
    ('Consider the universal wave equation, and what you know about wavelengths in closed air columns. This is new, but the "first fundamental frequency" of a closed air column would be the frequency corresponding to a quarter-wavelength in the column',
     '파동의 기본 방정식과 닫힌 공기 기둥의 파장에 대해 알고 있는 것을 생각해 보세요. 이것은 새로운 것이지만, 닫힌 공기 기둥의 "첫 번째 기본 진동수"는 기둥에서 파장의 4분의 1에 해당하는 진동수입니다'),
    ("This is a new situation, so try to transfer your understanding to this new arrangement of waves.",
     "이것은 새로운 상황이므로, 이해한 내용을 이 새로운 파동 배열에 적용해 보세요."),
    ("The first resonant frequency would be the frequency corresponding to",
     "첫 번째 공명 진동수는"),
    ("By applying my prior knowledge to this new situation, the first resonant frequency is 180 Hz and the second resonant frequency is 530 Hz.",
     "이전 지식을 새로운 상황에 적용하면, 첫 번째 공명 진동수는 180 Hz이고 두 번째 공명 진동수는 530 Hz입니다."),
    ("two significant digits are used in the statement since the given length and speed each have two significant digits.",
     "주어진 길이와 속력이 각각 유효 숫자 2자리이므로 2자리로 나타냅니다."),

    # Lab reports
    ("Lab reports", "실험 보고서"),
    ("A lab report is a piece of scientific writing. Lab reports follow a standard structure so that the interesting information contained can be reliably interpreted by other scientists. A lab report is a scientist's evidence that they performed the stated experiment, found the given results, and made the stated conclusions in a transparent way. They are written in a way that can be repeated by other scientists wishing to verify the results.",
     "실험 보고서는 과학적 글쓰기의 한 형태입니다. 실험 보고서는 표준 구조를 따르므로, 포함된 흥미로운 정보를 다른 과학자들이 신뢰성 있게 해석할 수 있습니다. 실험 보고서는 과학자가 명시된 실험을 수행하고, 주어진 결과를 찾고, 명시된 결론을 투명한 방식으로 내렸다는 증거입니다. 결과를 검증하려는 다른 과학자들이 반복할 수 있는 방식으로 작성됩니다."),
    ("One of the expectations of this course is for you to understand and create lab reports.",
     "이 과정의 기대 사항 중 하나는 실험 보고서를 이해하고 작성하는 것입니다."),
    ("If you would like to refer to a sample lab report, you can access the example below. This is an example report for a slightly different experiment. You may use it to better format your lab report. You do not need to perform this experiment.",
     "샘플 실험 보고서를 참고하려면 아래 예시에 접근할 수 있습니다. 이것은 약간 다른 실험에 대한 예시 보고서입니다. 실험 보고서 형식을 개선하는 데 사용할 수 있습니다. 이 실험을 수행할 필요는 없습니다."),
    ("Press here for a sample lab report.", "샘플 실험 보고서를 보려면 여기를 누르세요."),
    ("Explore the following lab activity.", "다음 실험 활동을 탐구하세요."),
    ("Lab activity", "실험 활동"),
    ("Speed of sound in air using a closed air column lab",
     "닫힌 공기 기둥을 이용한 공기 중 음속 측정 실험"),
    ("Your task is now to review the lab and then explore the video. Then, complete the analysis and conclusion question. You will refer back to this activity in the Unit 1 Assignment.",
     "이제 실험을 검토한 다음 영상을 탐구하세요. 그런 다음 분석과 결론 질문을 완성하세요. 단원 1 과제에서 이 활동을 다시 참고하게 됩니다."),
    ("Purpose", "목적"),
    ("Materials", "재료"),
    ("Apparatus", "실험 장치"),
    ("Method", "방법"),
    ("Analysis", "분석"),
    ("Conclusion", "결론"),
    ("To calculate the speed of sound in air using the resonant lengths of a closed air column.",
     "닫힌 공기 기둥의 공명 길이를 이용하여 공기 중 음속을 계산한다."),
    ("tube, water, graduated cylinder, tuning fork, mallet, ruler",
     "관, 물, 눈금 실린더, 소리굽쇠, 망치, 자"),
    ("Set up of air column lab", "공기 기둥 실험 장치 설치"),
    ("Fill a graduated cylinder with water.", "눈금 실린더에 물을 채웁니다."),
    ("Place a tube inside (making the end in the water a closed end).",
     "관을 안에 넣습니다 (물 속의 끝을 닫힌 끝으로 만듭니다)."),
    ("Sound the tuning fork (f = 1024 Hz).", "소리굽쇠를 칩니다 (f = 1024 Hz)."),
    ("Place it close to the open end of the closed air column.",
     "닫힌 공기 기둥의 열린 끝 가까이에 놓습니다."),
    ("Raise it from the water until a loud sound (resonance) is observed.",
     "큰 소리(공명)가 관찰될 때까지 물에서 올립니다."),
    ("Measure the length of the air column. This is the resonant length",
     "공기 기둥의 길이를 측정합니다. 이것이 공명 길이"),
    ("Repeat the procedure until the second resonant length",
     "두 번째 공명 길이"),
    ("is observed.", "가 관찰될 때까지 절차를 반복합니다."),
    ("Complete the following questions.", "다음 질문을 완성하세요."),
    ("Using the equations for the resonant lengths, calculate the wavelength (in metres).",
     "공명 길이 공식을 사용하여 파장(미터 단위)을 계산하세요."),
    ("Do this for both", "두"),
    ("Using the universal wave equation", "파동의 기본 방정식"),
    (", calculate the speed of sound in air using the frequency of the tuning fork (f = 1024 Hz) and the wavelength calculated in Question 1.",
     "을 사용하여, 소리굽쇠의 진동수 (f = 1024 Hz)와 문제 1에서 계산한 파장으로 공기 중 음속을 계산하세요."),
    ("Find the theoretical speed in air at 23.0", "23.0"),
    ("C using the equation:", "°C에서의 이론적 음속을 다음 공식을 사용하여 구하세요:"),
    ("Find the percent error for the experimental speed of sound calculations compared to the theoretical speed of sound in air. Use the formula:",
     "실험적 음속 계산값과 이론적 공기 중 음속을 비교한 백분율 오차를 구하세요. 다음 공식을 사용하세요:"),
    ("Percent Error", "백분율 오차"),
    ("experimental value", "실험값"),
    ("theoretical value", "이론값"),
    ("Write your own conclusion for the experiment based on the purpose of the lab, your results, and your analysis.",
     "실험 목적, 결과, 분석을 바탕으로 실험에 대한 자신만의 결론을 작성하세요."),
    ("Access the following video, which freezes a few times (so you can read the on-screen descriptions), to experience the apparatus and the results of the experiment.",
     "다음 영상을 시청하세요. 영상이 몇 번 멈추므로 (화면의 설명을 읽을 수 있도록) 실험 장치와 결과를 확인할 수 있습니다."),

    # Open air columns
    ("Open air columns", "열린 공기 기둥"),
    ("So far you have investigated standing waves with two fixed ends (nodes at each end), and standing waves with one fixed and one free end (one end is a node and one is an antinode). Another type of air column exists, where a long cylinder is open at both ends. This is called an open air column. This new type is formed when both ends of the wave are antinodes.",
     "지금까지 양쪽 끝이 고정된 정상파(양쪽 끝에 마디)와 한쪽이 고정되고 한쪽이 자유인 정상파(한쪽 끝이 마디이고 한쪽이 배)를 조사했습니다. 긴 원통의 양쪽 끝이 모두 열린 다른 유형의 공기 기둥이 있습니다. 이것을 열린 공기 기둥이라고 합니다. 이 새로운 유형은 파동의 양쪽 끝이 모두 배일 때 형성됩니다."),
    ("The following diagrams display the standing waves formed in an air column that is open both ends.",
     "다음 그림들은 양쪽 끝이 모두 열린 공기 기둥에서 형성되는 정상파를 보여줍니다."),
    ("First resonant length", "첫 번째 공명 길이"),
    ("Second resonant length", "두 번째 공명 길이"),
    ("Third resonant length", "세 번째 공명 길이"),
    ("The following diagram is of first length of air that will cause a loud sound from the tuning fork. The length is equal to",
     "다음 그림은 소리굽쇠에서 큰 소리를 만드는 첫 번째 공기 길이입니다. 길이는"),
    ("Given speed of sound and the frequency of the tuning fork,",
     "음속과 소리굽쇠의 진동수가 주어지면,"),
    ("can be used to find the wavelength if needed.",
     "필요시 파동의 기본 방정식을 사용하여 파장을 구할 수 있습니다."),
    ("The following diagram is of the second length of air that will cause a loud sound from the tuning fork. The length is equal to",
     "다음 그림은 소리굽쇠에서 큰 소리를 만드는 두 번째 공기 길이입니다. 길이는"),
    ("The following diagram is of third length of air that will cause a loud sound from the tuning fork. The length is equal to",
     "다음 그림은 소리굽쇠에서 큰 소리를 만드는 세 번째 공기 길이입니다. 길이는"),

    # Open air column example
    ("An organ pipe, which is 1.2 m long and open at both ends, produces a note with the fundamental frequency. If the speed of sound in air is 345 m/s, what is the fundamental frequency?",
     "양쪽 끝이 열린 길이 1.2 m의 오르간 파이프가 기본 진동수의 음을 냅니다. 공기 중 음속이 345 m/s일 때, 기본 진동수는 얼마인가요?"),
    ("Then, use the universal wave equation to find the frequency.",
     "그런 다음, 파동의 기본 방정식을 사용하여 진동수를 구합니다."),
    ("Therefore, the fundamental frequency of the pipe is 144 Hz.",
     "따라서, 파이프의 기본 진동수는 144 Hz입니다."),

    # Open air column summary
    ("If we know the frequency of the sound wave, we can predict the length of the open air column that is needed to create a resonant length. The resonant length is important because that is what creates the loud sound. If the air column was not the correct length, the sound would not get amplified because there would be no resonance.",
     "음파의 진동수를 알면, 공명 길이를 만드는 데 필요한 열린 공기 기둥의 길이를 예측할 수 있습니다. 공명 길이는 큰 소리를 만드는 것이기 때문에 중요합니다. 공기 기둥이 올바른 길이가 아니면, 공명이 없기 때문에 소리가 증폭되지 않습니다."),

    # Open air column problems
    ("Now try the following questions about waves in open air columns. Compare your answers to the suggested answers.",
     "다음 열린 공기 기둥의 파동에 관한 문제를 풀어 보세요. 풀이 예시와 답을 비교해 보세요."),
    ("1. A tuning fork with a frequency of 380 Hz is sounded near the top of an open air column when the speed of sound is 344 m/s. What is the wavelength of the sound? What are the first three resonant lengths?",
     "1. 음속이 344 m/s일 때, 진동수 380 Hz의 소리굽쇠를 열린 공기 기둥 위에서 칩니다. 소리의 파장은 얼마인가요? 처음 세 공명 길이는 얼마인가요?"),
    ("With two significant digits, this will probably be the value that limits the significant digits of our reported answer.",
     "유효 숫자 2자리이므로, 이것이 최종 답의 유효 숫자를 제한할 것입니다."),
    ("The wavelength is 0.91 m and the first three resonant lengths are 0.45 m, 0.91 m, and 1.4 m.",
     "파장은 0.91 m이고 처음 세 공명 길이는 0.45 m, 0.91 m, 1.4 m입니다."),

    # Problem 2
    ("2. A 450 Hz tuning fork is held at the top of an open air column when the temperature of the air is 18",
     "2. 공기 온도가 18"),
    ("How much longer is the third resonant length than the second resonant length?",
     "세 번째 공명 길이는 두 번째 공명 길이보다 얼마나 더 긴가요?"),
    ("First, find the speed of sound.", "먼저 음속을 구합니다."),
    ("The third resonant length is 0.38 m longer than the second resonant length.",
     "세 번째 공명 길이는 두 번째 공명 길이보다 0.38 m 더 깁니다."),
    ("An interesting observation: since each resonant length is one",
     "흥미로운 관찰: 각 공명 길이는 이전 것보다"),
    ("longer than the previous one, all pairs of consecutive resonant lengths will also have this difference.",
     "만큼 더 기므로, 연속된 모든 공명 길이 쌍도 이 차이를 가집니다."),

    # Problem 3
    ("3. An open air column is set up inside a home so that it will resonate with a tuning fork, using its first resonant length. Both the air column and tuning fork are taken outside in the wintertime, but now, resonance is not observed. Explain why this happens.",
     "3. 열린 공기 기둥을 집 안에 설치하여 첫 번째 공명 길이로 소리굽쇠와 공명하도록 합니다. 공기 기둥과 소리굽쇠를 모두 겨울에 밖으로 가져갔지만, 이제 공명이 관찰되지 않습니다. 이유를 설명하세요."),
    ("Resonance in an air column is related to the frequency, and the speed of sound, combining to make just the right wavelength.",
     "공기 기둥에서의 공명은 진동수와 음속이 결합하여 정확한 파장을 만드는 것과 관련됩니다."),
    ("Outside in the wintertime, the temperature of the air is lower and so the speed of sound is lower.",
     "겨울에 밖에서는 공기 온도가 낮으므로 음속도 낮습니다."),
    ("Since the speed of sound is now lower, the wavelength associated with the tuning fork's frequency is lower and no longer matches the resonant length of the open air column. As a result, the constructive interference required for resonance does not occur, and resonance is not observed.",
     "음속이 낮아졌으므로, 소리굽쇠의 진동수에 해당하는 파장도 짧아져 열린 공기 기둥의 공명 길이와 더 이상 일치하지 않습니다. 그 결과, 공명에 필요한 보강 간섭이 발생하지 않아 공명이 관찰되지 않습니다."),

    # Problem 4
    ("4. Explain whether a tuning fork with a lower or a higher frequency will be required to cause resonance outside.",
     "4. 밖에서 공명을 일으키려면 더 낮은 진동수의 소리굽쇠가 필요한지 더 높은 진동수의 소리굽쇠가 필요한지 설명하세요."),
    ("The speed of sound outside is slower. Since",
     "밖에서의 음속은 더 느립니다."),
    (", to keep wavelength the same with the smaller speed, frequency would also need to be made smaller. We would need a tuning fork with a lower frequency to cause resonance outside. This is one of the reasons it's important to tune an instrument in the same environment it will be played.",
     ", 더 느린 속력에서 파장을 같게 유지하려면, 진동수도 작아져야 합니다. 밖에서 공명을 일으키려면 더 낮은 진동수의 소리굽쇠가 필요합니다. 이것이 악기를 연주할 환경과 같은 환경에서 조율하는 것이 중요한 이유 중 하나입니다."),

    # Application: Instruments
    ("Application: Instruments", "응용: 악기"),
    ("Wind instruments", "관악기"),
    ("String instruments", "현악기"),
    ("Human voice", "사람의 목소리"),
    ("Percussion", "타악기"),
    ("All wind instruments contain air columns that cause resonance to produce sound.", "모든 관악기는 소리를 내기 위해 공명을 일으키는 공기 기둥을 포함합니다."),
    ("The frequency of the sound produced depends on the length of the air column.", "발생하는 소리의 진동수는 공기 기둥의 길이에 따라 달라집니다."),
    ("In general, larger instruments have longer air columns and lower frequency sound.", "일반적으로, 더 큰 악기는 더 긴 공기 기둥과 더 낮은 진동수의 소리를 가집니다."),
    ("Smaller wind instruments will have shorter air columns and will produce higher frequency sounds.", "더 작은 관악기는 더 짧은 공기 기둥을 가지며 더 높은 진동수의 소리를 냅니다."),
    ("In some wind instruments the length of the air column is fixed, while in others, the length can be changed.", "일부 관악기에서는 공기 기둥의 길이가 고정되어 있고, 다른 것에서는 길이를 바꿀 수 있습니다."),
    ("In addition, many wind instruments have air columns that are bent into loops to decrease the overall length of the instrument.", "또한, 많은 관악기는 악기의 전체 길이를 줄이기 위해 공기 기둥이 루프 형태로 구부러져 있습니다."),
    ("A trombone, for example, uses a variable column length and is bent into a loop to reduce its overall length.", "예를 들어, 트롬본은 가변 기둥 길이를 사용하며 전체 길이를 줄이기 위해 루프로 구부러져 있습니다."),
    ("To produce sound in the air columns in wind instruments, students need something that will vibrate back and forth.", "관악기의 공기 기둥에서 소리를 내려면, 앞뒤로 진동하는 것이 필요합니다."),
    ("One way to make sound is to blow air into the tube and past a membrane called a reed. The turbulence from the wind will cause the reed to vibrate and produce sound.", "소리를 내는 한 가지 방법은 관에 공기를 불어 리드라고 하는 막을 지나가게 하는 것입니다. 바람의 난류가 리드를 진동시켜 소리를 만듭니다."),
    ("Instruments that use this method include the saxophone and the clarinet.", "이 방법을 사용하는 악기에는 색소폰과 클라리넷이 있습니다."),
    ("Another way to produce sound in a wind instrument is to use the player's lips as the source of vibration. In this case, the player's lips act like a double reed. Typically, this method is used with brass instruments like the trombone, trumpet, and tuba.",
     "관악기에서 소리를 내는 다른 방법은 연주자의 입술을 진동원으로 사용하는 것입니다. 이 경우, 연주자의 입술이 이중 리드처럼 작용합니다. 일반적으로 이 방법은 트롬본, 트럼펫, 튜바 같은 금관악기에 사용됩니다."),
    ("String instruments, such as a piano, guitar, and violin, use a vibrator (the string), as well as a resonator, to produce sound. The resonator is similar to the box closed at one end that is used to magnify the sound of tuning forks. Normally, a string by itself will not produce a very loud sound or even a very pleasant one.",
     "피아노, 기타, 바이올린 같은 현악기는 진동체(현)와 공명체를 사용하여 소리를 냅니다. 공명체는 소리굽쇠의 소리를 증폭시키는 데 사용되는 한쪽 끝이 닫힌 상자와 유사합니다. 보통, 현 자체만으로는 매우 큰 소리나 쾌적한 소리를 내지 못합니다."),
    ("Focusing the sound of a string into a resonator increases not only the volume of the sound through resonance, but also the quality of the sound.",
     "현의 소리를 공명체에 집중시키면 공명을 통해 소리의 크기뿐만 아니라 음질도 향상됩니다."),
    ("Some string instruments are played by plucking or striking the strings.", "일부 현악기는 현을 뜯거나 쳐서 연주합니다."),
    ("Plucking a string in the centre will cause it to vibrate in its fundamental mode, with only one loop in the string.", "현의 중앙을 뜯으면 현이 하나의 루프만 있는 기본 모드로 진동합니다."),
    ("Plucking the string one-quarter of its entire length from one fixed end will cause it to vibrate with more than one frequency, simultaneously.", "고정된 한쪽 끝에서 전체 길이의 4분의 1 지점을 뜯으면, 동시에 둘 이상의 진동수로 진동하게 됩니다."),
    ("The standing wave pattern produced in the string could be the superposition of a single loop interfering with another standing wave pattern with two loops.", "현에서 만들어지는 정상파 패턴은 단일 루프와 두 개의 루프를 가진 다른 정상파 패턴의 중첩일 수 있습니다."),
    ("This interference pattern resulting from more than one frequency vibrating at a time will change the quality of the sound produced.", "동시에 둘 이상의 진동수가 진동하여 만들어지는 이 간섭 패턴은 발생하는 소리의 음질을 변화시킵니다."),
    ("The human voice is the oldest form of a musical instrument. It consists of three main parts: the lungs, which provide the source of air; the vocal cords, which act as a double-reed vibrator; and the lower throat, which acts as a resonator.",
     "사람의 목소리는 가장 오래된 형태의 악기입니다. 세 가지 주요 부분으로 구성됩니다: 공기원을 제공하는 폐, 이중 리드 진동체 역할을 하는 성대, 그리고 공명체 역할을 하는 하부 인후입니다."),
    ("Typically, air from the lungs is forced past the vocal cords, causing them to vibrate. The frequency of the vibration is controlled by the tension in the cords, as well as their size. Loudness will increase if the amount of air forced from the lungs is increased. The quality of the sound is determined by resonance in the lower throat. Quality can be improved with training.",
     "일반적으로, 폐에서 나온 공기가 성대를 지나면서 성대를 진동시킵니다. 진동의 진동수는 성대의 장력과 크기에 의해 조절됩니다. 폐에서 밀어내는 공기량이 증가하면 음량이 커집니다. 소리의 음질은 하부 인후의 공명에 의해 결정됩니다. 훈련으로 음질을 개선할 수 있습니다."),
    ("Percussion instruments are played by striking a hard object, such as a hammer, bar, or stick, against another object. The most commonly used percussion instrument today is the drum. A typical drum set also includes one or more cymbal. Any percussion instrument vibrates when struck. It is the vibration of the object that produces the sound. Often, these instruments are used to keep the time for a band or orchestra. A drum consists of a membrane stretched over a cylinder.",
     "타악기는 망치, 막대, 스틱 같은 단단한 물체로 다른 물체를 쳐서 연주합니다. 오늘날 가장 일반적으로 사용되는 타악기는 드럼입니다. 일반적인 드럼 세트에는 하나 이상의 심벌즈도 포함됩니다. 모든 타악기는 쳤을 때 진동합니다. 소리를 내는 것은 물체의 진동입니다. 이 악기들은 종종 밴드나 오케스트라의 박자를 맞추는 데 사용됩니다. 드럼은 원통 위에 막을 팽팽하게 늘인 것으로 구성됩니다."),
    ("When the membrane is struck it vibrates back and forth, producing a two-dimensional standing wave that helps to amplify the sound. In addition, the sound echoes throughout the cylindrical frame, which causes resonance and improves the quality of the sound. The tighter the membrane is stretched across the hollow cylindrical frame, and the smaller the drum is, the higher the frequency of sound will be.",
     "막을 치면 앞뒤로 진동하여 소리를 증폭시키는 2차원 정상파를 만듭니다. 또한, 소리가 원통형 프레임 전체에 반향되어 공명을 일으키고 음질을 향상시킵니다. 막이 빈 원통형 프레임에 더 팽팽하게 당겨질수록, 그리고 드럼이 작을수록, 소리의 진동수가 높아집니다."),

    # Consolidation - sea shells
    ("Putting it all together", "종합하기"),
    ("Sea shells: Magic or science?", "조개껍데기: 마법인가 과학인가?"),
    ("If a person holds up a sea shell to their ear, it is said they will hear the sea. Record questions that you might have about this situation.",
     "조개껍데기를 귀에 대면 바다 소리가 들린다고 합니다. 이 상황에 대해 가질 수 있는 질문을 기록하세요."),
    ("Access the following video for an explanation of what causes the sound heard in a sea shell.",
     "조개껍데기에서 들리는 소리의 원인에 대한 설명을 다음 영상에서 확인하세요."),

    # Indigenous content
    ("Connecting our globe", "세계와의 연결"),
    ("In Indigenous communities across Canada, drums are an integral part of many First Nations,",
     "캐나다 전역의 원주민 공동체에서, 드럼은 많은 퍼스트 네이션,"),
    ("tis, and Inuit cultures.", "메티, 이누이트 문화의 필수적인 부분입니다."),
    ("Some Indigenous peoples use large drums at gatherings such as powwows or socials as well as small hand drums that a person can hold and play.",
     "일부 원주민은 파우와우나 사교 모임 같은 행사에서 큰 드럼을 사용하며, 한 사람이 들고 연주할 수 있는 작은 핸드 드럼도 사용합니다."),
    ("Drums are constructed based on the distinct geography and traditions of a particular community.",
     "드럼은 특정 공동체의 고유한 지리와 전통에 따라 제작됩니다."),
    ("For example, an Inuit hand drum, also known as a qilaut, is made out of caribou and seal skin, while a Haudenosaunee water drum is made from a local tree such as cedar or maple with deer hide stretched over top.",
     "예를 들어, 킬라우트라고도 알려진 이누이트 핸드 드럼은 순록과 물범 가죽으로 만들어지며, 하우데노소니 워터 드럼은 삼나무나 단풍나무 같은 지역 나무에 사슴 가죽을 위에 팽팽하게 늘여 만듭니다."),
    ("Qilaut from Eskimo Point, an Inuit settlement in the north of Canada.",
     "캐나다 북부의 이누이트 정착지인 에스키모 포인트의 킬라우트."),
    ("In First Nations,", "퍼스트 네이션,"),
    ("tis, and Inuit communities, drumming is usually combined with dancing and singing.",
     "메티, 이누이트 공동체에서 드럼 연주는 보통 춤과 노래와 결합됩니다."),
    ("The role of the drum extends beyond the production of sounds or music for Indigenous communities. It also provides spiritual and social connections as well as healing.",
     "원주민 공동체에서 드럼의 역할은 소리나 음악의 생산을 넘어섭니다. 드럼은 영적, 사회적 연결과 치유도 제공합니다."),
    ("Drums differ based on the community in which they are from and they are made from the materials that are local to those communities.",
     "드럼은 출신 공동체에 따라 다르며, 해당 공동체 지역의 재료로 만들어집니다."),
    ('For example, the Inuit of Inuvialuit (meaning "the real people") are from the Western Arctic area, in the modern-day Northwest Territories, and are from one of the four Inuit regions in Canada.',
     '예를 들어, 이누비알루이트의 이누이트("진정한 사람들"이라는 뜻)는 현대의 노스웨스트 준주에 해당하는 서부 북극 지역 출신이며, 캐나다의 네 이누이트 지역 중 하나에 속합니다.'),
    ("In the following video, observe how members of the The Ulukhaktok Western Drummers and Dancers from Inuvialuit use drums made of caribou skin. The teachings and traditions around the drum also vary from community to community.",
     "다음 영상에서, 이누비알루이트의 울루크학톡 서부 드러머와 댄서 단원들이 순록 가죽으로 만든 드럼을 어떻게 사용하는지 관찰하세요. 드럼에 관한 가르침과 전통도 공동체마다 다릅니다."),
    ("The following video about drumming explains the significance of the drum to Ojibwe people and how it is made.",
     "다음 드럼 연주에 관한 영상은 오지브웨 사람들에게 드럼의 의미와 드럼이 어떻게 만들어지는지 설명합니다."),
    ("While exploring these videos, it is important to understand that Indigenous ways of knowing, being and doing are equally important to scientific ways. These two ways are not contradictory, rather they often overlap as Indigenous knowledge includes scientific knowledge and vice versa. It is important that Indigenous knowledge and scientific knowledge are both ways of understanding the world around us.",
     "이 영상들을 탐구할 때, 원주민의 앎, 존재, 행동의 방식이 과학적 방식만큼 중요하다는 것을 이해하는 것이 중요합니다. 이 두 방식은 모순되지 않으며, 원주민 지식이 과학적 지식을 포함하고 그 반대도 마찬가지이므로 종종 겹칩니다. 원주민 지식과 과학적 지식 모두 우리 주변 세계를 이해하는 방법이라는 것이 중요합니다."),
    ("Read", "읽기"),
    ("The following article", "다음 기사"),
    ("Meet the Scientists Embracing Traditional Indigenous Knowledge", "Meet the Scientists Embracing Traditional Indigenous Knowledge"),
    ("by Jimmy Thomson in", "의 저자 Jimmy Thomson ("),
    ("The Narwhal", "The Narwhal"),
    ("discusses the overlap between", ")은"),
    ('"Indigenous" and "western" science.', '"원주민" 과학과 "서양" 과학 사이의 겹침을 논의합니다.'),
    ("Now you have completed all of of the learning activities in this unit, use the following prompts to complete some independent research. Record your findings in your notebook.",
     "이 단원의 모든 학습 활동을 완료했으므로, 다음 지시를 사용하여 독립적인 연구를 완성하세요. 연구 결과를 노트에 기록하세요."),
    ("Choose a career you are interested in and that is related to the topics presented in this unit. Research the education and training necessary to pursue this career.",
     "이 단원에서 다룬 주제와 관련된 관심 있는 직업을 선택하세요. 이 직업을 추구하는 데 필요한 교육과 훈련을 조사하세요."),
    ("Choose a famous Canadian physicist in a field of physics related to the content of this unit. Prepare a short biography including the name of the physicist, when they made their contribution to physics knowledge, what they contributed, and how it benefited society.",
     "이 단원의 내용과 관련된 물리학 분야의 유명한 캐나다 물리학자를 선택하세요. 물리학자의 이름, 물리학 지식에 기여한 시기, 기여 내용, 그리고 사회에 어떤 이점을 주었는지를 포함하는 짧은 전기를 준비하세요."),
    ("Review the vocabulary related to resonance. Ensure that you have a good understanding of how to use these words to describe the physics involved.",
     "공명과 관련된 어휘를 복습하세요. 이 단어들을 사용하여 관련 물리학을 설명하는 방법을 잘 이해하고 있는지 확인하세요."),
    ("Learning Activity 1.5 Assignment", "학습 활동 1.5 과제"),
    ("When you are ready, go to the following page to learn more about 1.5 Assignment.",
     "준비가 되면, 다음 페이지로 이동하여 1.5 과제에 대해 자세히 알아보세요."),
    ("Transferable skills survey", "전이 가능한 기술 설문"),
    ("Having completed the unit, take the opportunity to review your demonstration of Ontario's Transferable Skills, introduced in 1.1. Complete the Unit 1 Transferable Skills Survey to share your assessment and specific evidence for that rating.",
     "단원을 완료했으므로, 1.1에서 소개된 온타리오 전이 가능한 기술의 시연을 검토할 기회를 가지세요. 단원 1 전이 가능한 기술 설문을 완성하여 평가와 그 평가에 대한 구체적인 근거를 공유하세요."),
    ("Press the Transferable Skills Survey button to access it.",
     "전이 가능한 기술 설문 버튼을 눌러 접근하세요."),
    ("Self-check quiz", "자기 점검 퀴즈"),
    ("Check your understanding!", "이해도를 확인하세요!"),
    ("Complete the following self-check quiz to determine where you are in your learning and what areas you need to focus on.",
     "다음 자기 점검 퀴즈를 풀어 현재 학습 위치와 집중해야 할 영역을 파악하세요."),
    ("This quiz is for feedback only, not part of your grade. You have unlimited attempts on this quiz. Take your time, do your best work, and reflect on any feedback provided.",
     "이 퀴즈는 피드백 전용이며 성적에 포함되지 않습니다. 이 퀴즈에 대한 시도 횟수는 무제한입니다. 충분한 시간을 가지고 최선을 다하며, 제공된 피드백을 되돌아보세요."),
    ("Press Quiz to access this tool.", "퀴즈 버튼을 눌러 도구에 접근하세요."),

    # String problems section
    ("the speed of the wave", "파동의 속력"),
    ("Write a sentence that responds to the question, including a consideration of significant digits.",
     "유효 숫자를 고려하여 질문에 답하는 문장을 작성하세요."),
    ("2. What is the wavelength of the fundamental frequency?", "2. 기본 진동수의 파장은 얼마인가요?"),
    ("The wavelength of the fundamental frequency is 8.0 m.", "기본 진동수의 파장은 8.0 m입니다."),
    ("3. What is the fundamental frequency of the string?", "3. 현의 기본 진동수는 얼마인가요?"),
    ("The fundamental frequency is 5.0 Hz.", "기본 진동수는 5.0 Hz입니다."),
    ("4. Find the frequency that will produce a standing wave with 3 loops.", "4. 3개의 루프를 가진 정상파를 만드는 진동수를 구하세요."),
    ("5. Identify another frequency that will produce a standing wave in the string. How many loops will it have?",
     "5. 현에서 정상파를 만드는 다른 진동수를 구하세요. 몇 개의 루프를 가지나요?"),
    ("6. Will a frequency of 23 Hz produce a standing wave in the string? Explain.",
     "6. 23 Hz의 진동수가 현에서 정상파를 만들 수 있나요? 설명하세요."),
    ("No, 23 Hz will not produce a standing wave. All standing waves have frequencies that are integer multiples of the fundamental frequency, 5.0 Hz. Since 23 is not a multiple of 5, 23 Hz cannot create a standing wave in this string.",
     "아니요, 23 Hz는 정상파를 만들지 못합니다. 모든 정상파는 기본 진동수 5.0 Hz의 정수 배인 진동수를 가집니다. 23은 5의 배수가 아니므로, 23 Hz는 이 현에서 정상파를 만들 수 없습니다."),
    ("In some other strings, other fundamental frequencies are possible. But in this string, the only frequencies that create standing waves are multiples of 5.0 Hz.",
     "다른 현에서는 다른 기본 진동수가 가능합니다. 하지만 이 현에서는 5.0 Hz의 배수인 진동수만 정상파를 만들 수 있습니다."),
    ("Since this question isn't just a calculation problem, it doesn't necessarily need the usual GUESS problem-solving structure. You certainly could use it, but it can be answered in words instead.",
     "이 문제는 단순한 계산 문제가 아니므로, 반드시 일반적인 GUESS 문제 풀이 구조를 따를 필요는 없습니다. 물론 사용할 수 있지만, 말로 답할 수도 있습니다."),
    ("Another frequency that will produce a standing wave is", "정상파를 만드는 다른 진동수는"),
    ("Any number could be chosen. 2 is a good choice,", "아무 수나 선택할 수 있습니다. 2가 좋은 선택이지만,"),
]

matched = 0
unmatched = 0
for eng, kor in TRANSLATIONS:
    content, success = flex_replace(content, eng, kor)
    if success:
        matched += 1
    else:
        unmatched += 1

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Matched: {matched}, Unmatched: {unmatched}")
